// Mocks generated by Mockito 5.2.0 from annotations
// in cinta_film/test/helpers/test_helper.dart.
// Do not manually edit this file.

import 'dart:async' as _i8;
import 'dart:convert' as _i18;
import 'dart:typed_data' as _i19;

import 'package:bloc/bloc.dart' as _i17;
import 'package:cinta_film/data/datasources/film/movie_local_data_source.dart'
    as _i13;
import 'package:cinta_film/data/datasources/film/movie_remote_data_source.dart'
    as _i11;
import 'package:cinta_film/data/lib_database.dart' as _i15;
import 'package:cinta_film/data/lib_server_fail.dart' as _i4;
import 'package:cinta_film/data/models/movie_detail_model.dart' as _i3;
import 'package:cinta_film/data/models/movie_model.dart' as _i12;
import 'package:cinta_film/data/models/movie_table.dart' as _i14;
import 'package:cinta_film/domain/entities/film.dart' as _i9;
import 'package:cinta_film/domain/entities/movie_detail.dart' as _i10;
import 'package:cinta_film/domain/get_data_film.dart' as _i5;
import 'package:cinta_film/presentasi/bloc/film_bloc.dart' as _i6;
import 'package:dartz/dartz.dart' as _i2;
import 'package:http/http.dart' as _i7;
import 'package:mockito/mockito.dart' as _i1;
import 'package:sqflite/sqflite.dart' as _i16;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

class _FakeEither_0<L, R> extends _i1.Fake implements _i2.Either<L, R> {}

class _FakeMovieDetailResponse_1 extends _i1.Fake
    implements _i3.MovieDetailResponse {}

class _FakeRepositoryFilm_2 extends _i1.Fake implements _i4.RepositoryFilm {}

class _FakeClassFilmTerPopuler_3 extends _i1.Fake
    implements _i5.ClassFilmTerPopuler {}

class _FakeMoviePopularState_4 extends _i1.Fake
    implements _i6.MoviePopularState {}

class _FakeClasFilmTayangSaatIni_5 extends _i1.Fake
    implements _i5.ClasFilmTayangSaatIni {}

class _FakeMovieNowPlayingState_6 extends _i1.Fake
    implements _i6.MovieNowPlayingState {}

class _FakeAmbilDataRekomendasiFilm_7 extends _i1.Fake
    implements _i5.AmbilDataRekomendasiFilm {}

class _FakeMovieRecommendationState_8 extends _i1.Fake
    implements _i6.MovieRecommendationState {}

class _FakeClassFilmRatingTerbaik_9 extends _i1.Fake
    implements _i5.ClassFilmRatingTerbaik {}

class _FakeMovieTopRatedState_10 extends _i1.Fake
    implements _i6.MovieTopRatedState {}

class _FakeClassCariFilm_11 extends _i1.Fake implements _i5.ClassCariFilm {}

class _FakeMovieSearchState_12 extends _i1.Fake
    implements _i6.MovieSearchState {}

class _FakeAmbilDataDetailFilm_13 extends _i1.Fake
    implements _i5.AmbilDataDetailFilm {}

class _FakeStateDetailFilm_14 extends _i1.Fake implements _i6.StateDetailFilm {}

class _FakeClassStatusDaftarTonton_15 extends _i1.Fake
    implements _i5.ClassStatusDaftarTonton {}

class _FakeClassDaftarTontonFilm_16 extends _i1.Fake
    implements _i5.ClassDaftarTontonFilm {}

class _FakeClassHapusDaftarTonton_17 extends _i1.Fake
    implements _i5.ClassHapusDaftarTonton {}

class _FakeClassSimpanDaftarTonton_18 extends _i1.Fake
    implements _i5.ClassSimpanDaftarTonton {}

class _FakeStateDaftarTontonFilm_19 extends _i1.Fake
    implements _i6.StateDaftarTontonFilm {}

class _FakeResponse_20 extends _i1.Fake implements _i7.Response {}

class _FakeStreamedResponse_21 extends _i1.Fake
    implements _i7.StreamedResponse {}

/// A class which mocks [RepositoryFilm].
///
/// See the documentation for Mockito's code generation for more information.
class MockRepositoryFilm extends _i1.Mock implements _i4.RepositoryFilm {
  MockRepositoryFilm() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i8.Future<_i2.Either<_i4.Failure, List<_i9.Film>>> filmTayangSaatIni() =>
      (super.noSuchMethod(Invocation.method(#filmTayangSaatIni, []),
          returnValue: Future<_i2.Either<_i4.Failure, List<_i9.Film>>>.value(
              _FakeEither_0<_i4.Failure, List<_i9.Film>>())) as _i8
          .Future<_i2.Either<_i4.Failure, List<_i9.Film>>>);
  @override
  _i8.Future<_i2.Either<_i4.Failure, List<_i9.Film>>>
      ambilDataFilmTerPopuler() =>
          (super.noSuchMethod(Invocation.method(#ambilDataFilmTerPopuler, []),
                  returnValue:
                      Future<_i2.Either<_i4.Failure, List<_i9.Film>>>.value(
                          _FakeEither_0<_i4.Failure, List<_i9.Film>>()))
              as _i8.Future<_i2.Either<_i4.Failure, List<_i9.Film>>>);
  @override
  _i8.Future<_i2.Either<_i4.Failure, List<_i9.Film>>>
      ambilFilmRatingTerbaik() =>
          (super.noSuchMethod(Invocation.method(#ambilFilmRatingTerbaik, []),
                  returnValue:
                      Future<_i2.Either<_i4.Failure, List<_i9.Film>>>.value(
                          _FakeEither_0<_i4.Failure, List<_i9.Film>>()))
              as _i8.Future<_i2.Either<_i4.Failure, List<_i9.Film>>>);
  @override
  _i8.Future<_i2.Either<_i4.Failure, _i10.MovieDetail>> getMovieDetail(
          int? id) =>
      (super.noSuchMethod(Invocation.method(#getMovieDetail, [id]),
          returnValue: Future<_i2.Either<_i4.Failure, _i10.MovieDetail>>.value(
              _FakeEither_0<_i4.Failure, _i10.MovieDetail>())) as _i8
          .Future<_i2.Either<_i4.Failure, _i10.MovieDetail>>);
  @override
  _i8.Future<_i2.Either<_i4.Failure, List<_i9.Film>>> getMovieRecommendations(
          int? id) =>
      (super.noSuchMethod(Invocation.method(#getMovieRecommendations, [id]),
          returnValue: Future<_i2.Either<_i4.Failure, List<_i9.Film>>>.value(
              _FakeEither_0<_i4.Failure, List<_i9.Film>>())) as _i8
          .Future<_i2.Either<_i4.Failure, List<_i9.Film>>>);
  @override
  _i8.Future<_i2.Either<_i4.Failure, List<_i9.Film>>> cariFilm(String? query) =>
      (super.noSuchMethod(Invocation.method(#cariFilm, [query]),
          returnValue: Future<_i2.Either<_i4.Failure, List<_i9.Film>>>.value(
              _FakeEither_0<_i4.Failure, List<_i9.Film>>())) as _i8
          .Future<_i2.Either<_i4.Failure, List<_i9.Film>>>);
  @override
  _i8.Future<_i2.Either<_i4.Failure, String>> daftarTonton(
          _i10.MovieDetail? film) =>
      (super.noSuchMethod(Invocation.method(#daftarTonton, [film]),
              returnValue: Future<_i2.Either<_i4.Failure, String>>.value(
                  _FakeEither_0<_i4.Failure, String>()))
          as _i8.Future<_i2.Either<_i4.Failure, String>>);
  @override
  _i8.Future<_i2.Either<_i4.Failure, String>> removewatchlist(
          _i10.MovieDetail? film) =>
      (super.noSuchMethod(Invocation.method(#removewatchlist, [film]),
              returnValue: Future<_i2.Either<_i4.Failure, String>>.value(
                  _FakeEither_0<_i4.Failure, String>()))
          as _i8.Future<_i2.Either<_i4.Failure, String>>);
  @override
  _i8.Future<bool> isAddedTowatchlist(int? id) =>
      (super.noSuchMethod(Invocation.method(#isAddedTowatchlist, [id]),
          returnValue: Future<bool>.value(false)) as _i8.Future<bool>);
  @override
  _i8.Future<_i2.Either<_i4.Failure, List<_i9.Film>>> ambilDaftarTontonFilm() =>
      (super.noSuchMethod(Invocation.method(#ambilDaftarTontonFilm, []),
          returnValue: Future<_i2.Either<_i4.Failure, List<_i9.Film>>>.value(
              _FakeEither_0<_i4.Failure, List<_i9.Film>>())) as _i8
          .Future<_i2.Either<_i4.Failure, List<_i9.Film>>>);
}

/// A class which mocks [MovieRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockMovieRemoteDataSource extends _i1.Mock
    implements _i11.MovieRemoteDataSource {
  MockMovieRemoteDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i8.Future<List<_i12.MovieModel>> filmTayangSaatIni() => (super.noSuchMethod(
          Invocation.method(#filmTayangSaatIni, []),
          returnValue: Future<List<_i12.MovieModel>>.value(<_i12.MovieModel>[]))
      as _i8.Future<List<_i12.MovieModel>>);
  @override
  _i8.Future<List<_i12.MovieModel>> ambilDataFilmTerPopuler() =>
      (super.noSuchMethod(Invocation.method(#ambilDataFilmTerPopuler, []),
              returnValue:
                  Future<List<_i12.MovieModel>>.value(<_i12.MovieModel>[]))
          as _i8.Future<List<_i12.MovieModel>>);
  @override
  _i8.Future<List<_i12.MovieModel>> ambilFilmRatingTerbaik() =>
      (super.noSuchMethod(Invocation.method(#ambilFilmRatingTerbaik, []),
              returnValue:
                  Future<List<_i12.MovieModel>>.value(<_i12.MovieModel>[]))
          as _i8.Future<List<_i12.MovieModel>>);
  @override
  _i8.Future<_i3.MovieDetailResponse> getMovieDetail(int? id) =>
      (super.noSuchMethod(Invocation.method(#getMovieDetail, [id]),
              returnValue: Future<_i3.MovieDetailResponse>.value(
                  _FakeMovieDetailResponse_1()))
          as _i8.Future<_i3.MovieDetailResponse>);
  @override
  _i8.Future<List<_i12.MovieModel>> getMovieRecommendations(int? id) =>
      (super.noSuchMethod(Invocation.method(#getMovieRecommendations, [id]),
              returnValue:
                  Future<List<_i12.MovieModel>>.value(<_i12.MovieModel>[]))
          as _i8.Future<List<_i12.MovieModel>>);
  @override
  _i8.Future<List<_i12.MovieModel>> cariFilm(String? query) =>
      (super.noSuchMethod(Invocation.method(#cariFilm, [query]),
              returnValue:
                  Future<List<_i12.MovieModel>>.value(<_i12.MovieModel>[]))
          as _i8.Future<List<_i12.MovieModel>>);
}

/// A class which mocks [MovieLocalDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockMovieLocalDataSource extends _i1.Mock
    implements _i13.MovieLocalDataSource {
  MockMovieLocalDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i8.Future<String> insertwatchlist(_i14.MovieTable? film) =>
      (super.noSuchMethod(Invocation.method(#insertwatchlist, [film]),
          returnValue: Future<String>.value('')) as _i8.Future<String>);
  @override
  _i8.Future<String> removewatchlist(_i14.MovieTable? film) =>
      (super.noSuchMethod(Invocation.method(#removewatchlist, [film]),
          returnValue: Future<String>.value('')) as _i8.Future<String>);
  @override
  _i8.Future<_i14.MovieTable?> getMovieById(int? id) =>
      (super.noSuchMethod(Invocation.method(#getMovieById, [id]),
              returnValue: Future<_i14.MovieTable?>.value())
          as _i8.Future<_i14.MovieTable?>);
  @override
  _i8.Future<List<_i14.MovieTable>> ambilDaftarTontonFilm() =>
      (super.noSuchMethod(Invocation.method(#ambilDaftarTontonFilm, []),
              returnValue:
                  Future<List<_i14.MovieTable>>.value(<_i14.MovieTable>[]))
          as _i8.Future<List<_i14.MovieTable>>);
}

/// A class which mocks [DatabaseHelper].
///
/// See the documentation for Mockito's code generation for more information.
class MockDatabaseHelper extends _i1.Mock implements _i15.DatabaseHelper {
  MockDatabaseHelper() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i8.Future<_i16.Database?> get database =>
      (super.noSuchMethod(Invocation.getter(#database),
              returnValue: Future<_i16.Database?>.value())
          as _i8.Future<_i16.Database?>);
  @override
  _i8.Future<int> insertwatchlist(_i14.MovieTable? film) =>
      (super.noSuchMethod(Invocation.method(#insertwatchlist, [film]),
          returnValue: Future<int>.value(0)) as _i8.Future<int>);
  @override
  _i8.Future<int> removewatchlist(_i14.MovieTable? film) =>
      (super.noSuchMethod(Invocation.method(#removewatchlist, [film]),
          returnValue: Future<int>.value(0)) as _i8.Future<int>);
  @override
  _i8.Future<Map<String, dynamic>?> getMovieById(int? id) =>
      (super.noSuchMethod(Invocation.method(#getMovieById, [id]),
              returnValue: Future<Map<String, dynamic>?>.value())
          as _i8.Future<Map<String, dynamic>?>);
  @override
  _i8.Future<List<Map<String, dynamic>>> ambilDaftarTontonFilm() =>
      (super.noSuchMethod(Invocation.method(#ambilDaftarTontonFilm, []),
              returnValue: Future<List<Map<String, dynamic>>>.value(
                  <Map<String, dynamic>>[]))
          as _i8.Future<List<Map<String, dynamic>>>);
}

/// A class which mocks [ClassDaftarTontonFilm].
///
/// See the documentation for Mockito's code generation for more information.
class MockClassDaftarTontonFilm extends _i1.Mock
    implements _i5.ClassDaftarTontonFilm {
  MockClassDaftarTontonFilm() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i8.Future<_i2.Either<_i4.Failure, List<_i9.Film>>> execute() =>
      (super.noSuchMethod(Invocation.method(#execute, []),
          returnValue: Future<_i2.Either<_i4.Failure, List<_i9.Film>>>.value(
              _FakeEither_0<_i4.Failure, List<_i9.Film>>())) as _i8
          .Future<_i2.Either<_i4.Failure, List<_i9.Film>>>);
}

/// A class which mocks [AmbilDataDetailFilm].
///
/// See the documentation for Mockito's code generation for more information.
class MockAmbilDataDetailFilm extends _i1.Mock
    implements _i5.AmbilDataDetailFilm {
  MockAmbilDataDetailFilm() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.RepositoryFilm get repository =>
      (super.noSuchMethod(Invocation.getter(#repository),
          returnValue: _FakeRepositoryFilm_2()) as _i4.RepositoryFilm);
  @override
  _i8.Future<_i2.Either<_i4.Failure, _i10.MovieDetail>> execute(int? id) =>
      (super.noSuchMethod(Invocation.method(#execute, [id]),
          returnValue: Future<_i2.Either<_i4.Failure, _i10.MovieDetail>>.value(
              _FakeEither_0<_i4.Failure, _i10.MovieDetail>())) as _i8
          .Future<_i2.Either<_i4.Failure, _i10.MovieDetail>>);
}

/// A class which mocks [ClassFilmRatingTerbaik].
///
/// See the documentation for Mockito's code generation for more information.
class MockClassFilmRatingTerbaik extends _i1.Mock
    implements _i5.ClassFilmRatingTerbaik {
  MockClassFilmRatingTerbaik() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.RepositoryFilm get repository =>
      (super.noSuchMethod(Invocation.getter(#repository),
          returnValue: _FakeRepositoryFilm_2()) as _i4.RepositoryFilm);
  @override
  _i8.Future<_i2.Either<_i4.Failure, List<_i9.Film>>> execute() =>
      (super.noSuchMethod(Invocation.method(#execute, []),
          returnValue: Future<_i2.Either<_i4.Failure, List<_i9.Film>>>.value(
              _FakeEither_0<_i4.Failure, List<_i9.Film>>())) as _i8
          .Future<_i2.Either<_i4.Failure, List<_i9.Film>>>);
}

/// A class which mocks [AmbilDataRekomendasiFilm].
///
/// See the documentation for Mockito's code generation for more information.
class MockAmbilDataRekomendasiFilm extends _i1.Mock
    implements _i5.AmbilDataRekomendasiFilm {
  MockAmbilDataRekomendasiFilm() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.RepositoryFilm get repository =>
      (super.noSuchMethod(Invocation.getter(#repository),
          returnValue: _FakeRepositoryFilm_2()) as _i4.RepositoryFilm);
  @override
  _i8.Future<_i2.Either<_i4.Failure, List<_i9.Film>>> execute(dynamic id) =>
      (super.noSuchMethod(Invocation.method(#execute, [id]),
          returnValue: Future<_i2.Either<_i4.Failure, List<_i9.Film>>>.value(
              _FakeEither_0<_i4.Failure, List<_i9.Film>>())) as _i8
          .Future<_i2.Either<_i4.Failure, List<_i9.Film>>>);
}

/// A class which mocks [ClassFilmTerPopuler].
///
/// See the documentation for Mockito's code generation for more information.
class MockClassFilmTerPopuler extends _i1.Mock
    implements _i5.ClassFilmTerPopuler {
  MockClassFilmTerPopuler() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.RepositoryFilm get repository =>
      (super.noSuchMethod(Invocation.getter(#repository),
          returnValue: _FakeRepositoryFilm_2()) as _i4.RepositoryFilm);
  @override
  _i8.Future<_i2.Either<_i4.Failure, List<_i9.Film>>> execute() =>
      (super.noSuchMethod(Invocation.method(#execute, []),
          returnValue: Future<_i2.Either<_i4.Failure, List<_i9.Film>>>.value(
              _FakeEither_0<_i4.Failure, List<_i9.Film>>())) as _i8
          .Future<_i2.Either<_i4.Failure, List<_i9.Film>>>);
}

/// A class which mocks [ClasFilmTayangSaatIni].
///
/// See the documentation for Mockito's code generation for more information.
class MockClasFilmTayangSaatIni extends _i1.Mock
    implements _i5.ClasFilmTayangSaatIni {
  MockClasFilmTayangSaatIni() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.RepositoryFilm get repository =>
      (super.noSuchMethod(Invocation.getter(#repository),
          returnValue: _FakeRepositoryFilm_2()) as _i4.RepositoryFilm);
  @override
  _i8.Future<_i2.Either<_i4.Failure, List<_i9.Film>>> execute() =>
      (super.noSuchMethod(Invocation.method(#execute, []),
          returnValue: Future<_i2.Either<_i4.Failure, List<_i9.Film>>>.value(
              _FakeEither_0<_i4.Failure, List<_i9.Film>>())) as _i8
          .Future<_i2.Either<_i4.Failure, List<_i9.Film>>>);
}

/// A class which mocks [ClassStatusDaftarTonton].
///
/// See the documentation for Mockito's code generation for more information.
class MockClassStatusDaftarTonton extends _i1.Mock
    implements _i5.ClassStatusDaftarTonton {
  MockClassStatusDaftarTonton() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.RepositoryFilm get repository =>
      (super.noSuchMethod(Invocation.getter(#repository),
          returnValue: _FakeRepositoryFilm_2()) as _i4.RepositoryFilm);
  @override
  _i8.Future<bool> execute(int? id) =>
      (super.noSuchMethod(Invocation.method(#execute, [id]),
          returnValue: Future<bool>.value(false)) as _i8.Future<bool>);
}

/// A class which mocks [ClassCariFilm].
///
/// See the documentation for Mockito's code generation for more information.
class MockClassCariFilm extends _i1.Mock implements _i5.ClassCariFilm {
  MockClassCariFilm() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.RepositoryFilm get repository =>
      (super.noSuchMethod(Invocation.getter(#repository),
          returnValue: _FakeRepositoryFilm_2()) as _i4.RepositoryFilm);
  @override
  _i8.Future<_i2.Either<_i4.Failure, List<_i9.Film>>> execute(String? query) =>
      (super.noSuchMethod(Invocation.method(#execute, [query]),
          returnValue: Future<_i2.Either<_i4.Failure, List<_i9.Film>>>.value(
              _FakeEither_0<_i4.Failure, List<_i9.Film>>())) as _i8
          .Future<_i2.Either<_i4.Failure, List<_i9.Film>>>);
}

/// A class which mocks [ClassSimpanDaftarTonton].
///
/// See the documentation for Mockito's code generation for more information.
class MockClassSimpanDaftarTonton extends _i1.Mock
    implements _i5.ClassSimpanDaftarTonton {
  MockClassSimpanDaftarTonton() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.RepositoryFilm get repository =>
      (super.noSuchMethod(Invocation.getter(#repository),
          returnValue: _FakeRepositoryFilm_2()) as _i4.RepositoryFilm);
  @override
  _i8.Future<_i2.Either<_i4.Failure, String>> execute(_i10.MovieDetail? film) =>
      (super.noSuchMethod(Invocation.method(#execute, [film]),
              returnValue: Future<_i2.Either<_i4.Failure, String>>.value(
                  _FakeEither_0<_i4.Failure, String>()))
          as _i8.Future<_i2.Either<_i4.Failure, String>>);
}

/// A class which mocks [ClassHapusDaftarTonton].
///
/// See the documentation for Mockito's code generation for more information.
class MockClassHapusDaftarTonton extends _i1.Mock
    implements _i5.ClassHapusDaftarTonton {
  MockClassHapusDaftarTonton() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.RepositoryFilm get repository =>
      (super.noSuchMethod(Invocation.getter(#repository),
          returnValue: _FakeRepositoryFilm_2()) as _i4.RepositoryFilm);
  @override
  _i8.Future<_i2.Either<_i4.Failure, String>> execute(_i10.MovieDetail? film) =>
      (super.noSuchMethod(Invocation.method(#execute, [film]),
              returnValue: Future<_i2.Either<_i4.Failure, String>>.value(
                  _FakeEither_0<_i4.Failure, String>()))
          as _i8.Future<_i2.Either<_i4.Failure, String>>);
}

/// A class which mocks [MoviePopularBloc].
///
/// See the documentation for Mockito's code generation for more information.
class MockMoviePopularBloc extends _i1.Mock implements _i6.MoviePopularBloc {
  MockMoviePopularBloc() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.ClassFilmTerPopuler get getPopularMovies => (super.noSuchMethod(
      Invocation.getter(#getPopularMovies),
      returnValue: _FakeClassFilmTerPopuler_3()) as _i5.ClassFilmTerPopuler);
  @override
  _i6.MoviePopularState get state =>
      (super.noSuchMethod(Invocation.getter(#state),
          returnValue: _FakeMoviePopularState_4()) as _i6.MoviePopularState);
  @override
  _i8.Stream<_i6.MoviePopularState> get stream =>
      (super.noSuchMethod(Invocation.getter(#stream),
              returnValue: Stream<_i6.MoviePopularState>.empty())
          as _i8.Stream<_i6.MoviePopularState>);
  @override
  bool get isClosed =>
      (super.noSuchMethod(Invocation.getter(#isClosed), returnValue: false)
          as bool);
  @override
  void add(_i6.MoviePopularEvent? event) =>
      super.noSuchMethod(Invocation.method(#add, [event]),
          returnValueForMissingStub: null);
  @override
  void onEvent(_i6.MoviePopularEvent? event) =>
      super.noSuchMethod(Invocation.method(#onEvent, [event]),
          returnValueForMissingStub: null);
  @override
  void emit(_i6.MoviePopularState? state) =>
      super.noSuchMethod(Invocation.method(#emit, [state]),
          returnValueForMissingStub: null);
  @override
  void on<E extends _i6.MoviePopularEvent>(
          _i17.EventHandler<E, _i6.MoviePopularState>? handler,
          {_i17.EventTransformer<E>? transformer}) =>
      super.noSuchMethod(
          Invocation.method(#on, [handler], {#transformer: transformer}),
          returnValueForMissingStub: null);
  @override
  void onTransition(
          _i17.Transition<_i6.MoviePopularEvent, _i6.MoviePopularState>?
              transition) =>
      super.noSuchMethod(Invocation.method(#onTransition, [transition]),
          returnValueForMissingStub: null);
  @override
  _i8.Future<void> close() => (super.noSuchMethod(Invocation.method(#close, []),
      returnValue: Future<void>.value(),
      returnValueForMissingStub: Future<void>.value()) as _i8.Future<void>);
  @override
  void onChange(_i17.Change<_i6.MoviePopularState>? change) =>
      super.noSuchMethod(Invocation.method(#onChange, [change]),
          returnValueForMissingStub: null);
  @override
  void addError(Object? error, [StackTrace? stackTrace]) =>
      super.noSuchMethod(Invocation.method(#addError, [error, stackTrace]),
          returnValueForMissingStub: null);
  @override
  void onError(Object? error, StackTrace? stackTrace) =>
      super.noSuchMethod(Invocation.method(#onError, [error, stackTrace]),
          returnValueForMissingStub: null);
}

/// A class which mocks [MovieNowPlayingBloc].
///
/// See the documentation for Mockito's code generation for more information.
class MockMovieNowPlayingBloc extends _i1.Mock
    implements _i6.MovieNowPlayingBloc {
  MockMovieNowPlayingBloc() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.ClasFilmTayangSaatIni get getNowPlayingMovies =>
      (super.noSuchMethod(Invocation.getter(#getNowPlayingMovies),
              returnValue: _FakeClasFilmTayangSaatIni_5())
          as _i5.ClasFilmTayangSaatIni);
  @override
  _i6.MovieNowPlayingState get state => (super.noSuchMethod(
      Invocation.getter(#state),
      returnValue: _FakeMovieNowPlayingState_6()) as _i6.MovieNowPlayingState);
  @override
  _i8.Stream<_i6.MovieNowPlayingState> get stream =>
      (super.noSuchMethod(Invocation.getter(#stream),
              returnValue: Stream<_i6.MovieNowPlayingState>.empty())
          as _i8.Stream<_i6.MovieNowPlayingState>);
  @override
  bool get isClosed =>
      (super.noSuchMethod(Invocation.getter(#isClosed), returnValue: false)
          as bool);
  @override
  void add(_i6.MovieNowPlayingEvent? event) =>
      super.noSuchMethod(Invocation.method(#add, [event]),
          returnValueForMissingStub: null);
  @override
  void onEvent(_i6.MovieNowPlayingEvent? event) =>
      super.noSuchMethod(Invocation.method(#onEvent, [event]),
          returnValueForMissingStub: null);
  @override
  void emit(_i6.MovieNowPlayingState? state) =>
      super.noSuchMethod(Invocation.method(#emit, [state]),
          returnValueForMissingStub: null);
  @override
  void on<E extends _i6.MovieNowPlayingEvent>(
          _i17.EventHandler<E, _i6.MovieNowPlayingState>? handler,
          {_i17.EventTransformer<E>? transformer}) =>
      super.noSuchMethod(
          Invocation.method(#on, [handler], {#transformer: transformer}),
          returnValueForMissingStub: null);
  @override
  void onTransition(
          _i17.Transition<_i6.MovieNowPlayingEvent, _i6.MovieNowPlayingState>?
              transition) =>
      super.noSuchMethod(Invocation.method(#onTransition, [transition]),
          returnValueForMissingStub: null);
  @override
  _i8.Future<void> close() => (super.noSuchMethod(Invocation.method(#close, []),
      returnValue: Future<void>.value(),
      returnValueForMissingStub: Future<void>.value()) as _i8.Future<void>);
  @override
  void onChange(_i17.Change<_i6.MovieNowPlayingState>? change) =>
      super.noSuchMethod(Invocation.method(#onChange, [change]),
          returnValueForMissingStub: null);
  @override
  void addError(Object? error, [StackTrace? stackTrace]) =>
      super.noSuchMethod(Invocation.method(#addError, [error, stackTrace]),
          returnValueForMissingStub: null);
  @override
  void onError(Object? error, StackTrace? stackTrace) =>
      super.noSuchMethod(Invocation.method(#onError, [error, stackTrace]),
          returnValueForMissingStub: null);
}

/// A class which mocks [MovieRecommendationBloc].
///
/// See the documentation for Mockito's code generation for more information.
class MockMovieRecommendationBloc extends _i1.Mock
    implements _i6.MovieRecommendationBloc {
  MockMovieRecommendationBloc() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.AmbilDataRekomendasiFilm get getMovieRecommendations =>
      (super.noSuchMethod(Invocation.getter(#getMovieRecommendations),
              returnValue: _FakeAmbilDataRekomendasiFilm_7())
          as _i5.AmbilDataRekomendasiFilm);
  @override
  _i6.MovieRecommendationState get state =>
      (super.noSuchMethod(Invocation.getter(#state),
              returnValue: _FakeMovieRecommendationState_8())
          as _i6.MovieRecommendationState);
  @override
  _i8.Stream<_i6.MovieRecommendationState> get stream =>
      (super.noSuchMethod(Invocation.getter(#stream),
              returnValue: Stream<_i6.MovieRecommendationState>.empty())
          as _i8.Stream<_i6.MovieRecommendationState>);
  @override
  bool get isClosed =>
      (super.noSuchMethod(Invocation.getter(#isClosed), returnValue: false)
          as bool);
  @override
  void add(_i6.MovieRecommendationEvent? event) =>
      super.noSuchMethod(Invocation.method(#add, [event]),
          returnValueForMissingStub: null);
  @override
  void onEvent(_i6.MovieRecommendationEvent? event) =>
      super.noSuchMethod(Invocation.method(#onEvent, [event]),
          returnValueForMissingStub: null);
  @override
  void emit(_i6.MovieRecommendationState? state) =>
      super.noSuchMethod(Invocation.method(#emit, [state]),
          returnValueForMissingStub: null);
  @override
  void on<E extends _i6.MovieRecommendationEvent>(
          _i17.EventHandler<E, _i6.MovieRecommendationState>? handler,
          {_i17.EventTransformer<E>? transformer}) =>
      super.noSuchMethod(
          Invocation.method(#on, [handler], {#transformer: transformer}),
          returnValueForMissingStub: null);
  @override
  void onTransition(
          _i17.Transition<_i6.MovieRecommendationEvent,
                  _i6.MovieRecommendationState>?
              transition) =>
      super.noSuchMethod(Invocation.method(#onTransition, [transition]),
          returnValueForMissingStub: null);
  @override
  _i8.Future<void> close() => (super.noSuchMethod(Invocation.method(#close, []),
      returnValue: Future<void>.value(),
      returnValueForMissingStub: Future<void>.value()) as _i8.Future<void>);
  @override
  void onChange(_i17.Change<_i6.MovieRecommendationState>? change) =>
      super.noSuchMethod(Invocation.method(#onChange, [change]),
          returnValueForMissingStub: null);
  @override
  void addError(Object? error, [StackTrace? stackTrace]) =>
      super.noSuchMethod(Invocation.method(#addError, [error, stackTrace]),
          returnValueForMissingStub: null);
  @override
  void onError(Object? error, StackTrace? stackTrace) =>
      super.noSuchMethod(Invocation.method(#onError, [error, stackTrace]),
          returnValueForMissingStub: null);
}

/// A class which mocks [MovieTopRatedBloc].
///
/// See the documentation for Mockito's code generation for more information.
class MockMovieTopRatedBloc extends _i1.Mock implements _i6.MovieTopRatedBloc {
  MockMovieTopRatedBloc() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.ClassFilmRatingTerbaik get getTopRatedMovies =>
      (super.noSuchMethod(Invocation.getter(#getTopRatedMovies),
              returnValue: _FakeClassFilmRatingTerbaik_9())
          as _i5.ClassFilmRatingTerbaik);
  @override
  _i6.MovieTopRatedState get state =>
      (super.noSuchMethod(Invocation.getter(#state),
          returnValue: _FakeMovieTopRatedState_10()) as _i6.MovieTopRatedState);
  @override
  _i8.Stream<_i6.MovieTopRatedState> get stream =>
      (super.noSuchMethod(Invocation.getter(#stream),
              returnValue: Stream<_i6.MovieTopRatedState>.empty())
          as _i8.Stream<_i6.MovieTopRatedState>);
  @override
  bool get isClosed =>
      (super.noSuchMethod(Invocation.getter(#isClosed), returnValue: false)
          as bool);
  @override
  void add(_i6.MovieTopRatedEvent? event) =>
      super.noSuchMethod(Invocation.method(#add, [event]),
          returnValueForMissingStub: null);
  @override
  void onEvent(_i6.MovieTopRatedEvent? event) =>
      super.noSuchMethod(Invocation.method(#onEvent, [event]),
          returnValueForMissingStub: null);
  @override
  void emit(_i6.MovieTopRatedState? state) =>
      super.noSuchMethod(Invocation.method(#emit, [state]),
          returnValueForMissingStub: null);
  @override
  void on<E extends _i6.MovieTopRatedEvent>(
          _i17.EventHandler<E, _i6.MovieTopRatedState>? handler,
          {_i17.EventTransformer<E>? transformer}) =>
      super.noSuchMethod(
          Invocation.method(#on, [handler], {#transformer: transformer}),
          returnValueForMissingStub: null);
  @override
  void onTransition(
          _i17.Transition<_i6.MovieTopRatedEvent, _i6.MovieTopRatedState>?
              transition) =>
      super.noSuchMethod(Invocation.method(#onTransition, [transition]),
          returnValueForMissingStub: null);
  @override
  _i8.Future<void> close() => (super.noSuchMethod(Invocation.method(#close, []),
      returnValue: Future<void>.value(),
      returnValueForMissingStub: Future<void>.value()) as _i8.Future<void>);
  @override
  void onChange(_i17.Change<_i6.MovieTopRatedState>? change) =>
      super.noSuchMethod(Invocation.method(#onChange, [change]),
          returnValueForMissingStub: null);
  @override
  void addError(Object? error, [StackTrace? stackTrace]) =>
      super.noSuchMethod(Invocation.method(#addError, [error, stackTrace]),
          returnValueForMissingStub: null);
  @override
  void onError(Object? error, StackTrace? stackTrace) =>
      super.noSuchMethod(Invocation.method(#onError, [error, stackTrace]),
          returnValueForMissingStub: null);
}

/// A class which mocks [MovieSearchBloc].
///
/// See the documentation for Mockito's code generation for more information.
class MockMovieSearchBloc extends _i1.Mock implements _i6.MovieSearchBloc {
  MockMovieSearchBloc() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.ClassCariFilm get searchMovies =>
      (super.noSuchMethod(Invocation.getter(#searchMovies),
          returnValue: _FakeClassCariFilm_11()) as _i5.ClassCariFilm);
  @override
  _i6.MovieSearchState get state =>
      (super.noSuchMethod(Invocation.getter(#state),
          returnValue: _FakeMovieSearchState_12()) as _i6.MovieSearchState);
  @override
  _i8.Stream<_i6.MovieSearchState> get stream =>
      (super.noSuchMethod(Invocation.getter(#stream),
              returnValue: Stream<_i6.MovieSearchState>.empty())
          as _i8.Stream<_i6.MovieSearchState>);
  @override
  bool get isClosed =>
      (super.noSuchMethod(Invocation.getter(#isClosed), returnValue: false)
          as bool);
  @override
  void add(_i6.MovieSearchEvent? event) =>
      super.noSuchMethod(Invocation.method(#add, [event]),
          returnValueForMissingStub: null);
  @override
  void onEvent(_i6.MovieSearchEvent? event) =>
      super.noSuchMethod(Invocation.method(#onEvent, [event]),
          returnValueForMissingStub: null);
  @override
  void emit(_i6.MovieSearchState? state) =>
      super.noSuchMethod(Invocation.method(#emit, [state]),
          returnValueForMissingStub: null);
  @override
  void on<E extends _i6.MovieSearchEvent>(
          _i17.EventHandler<E, _i6.MovieSearchState>? handler,
          {_i17.EventTransformer<E>? transformer}) =>
      super.noSuchMethod(
          Invocation.method(#on, [handler], {#transformer: transformer}),
          returnValueForMissingStub: null);
  @override
  void onTransition(
          _i17.Transition<_i6.MovieSearchEvent, _i6.MovieSearchState>?
              transition) =>
      super.noSuchMethod(Invocation.method(#onTransition, [transition]),
          returnValueForMissingStub: null);
  @override
  _i8.Future<void> close() => (super.noSuchMethod(Invocation.method(#close, []),
      returnValue: Future<void>.value(),
      returnValueForMissingStub: Future<void>.value()) as _i8.Future<void>);
  @override
  void onChange(_i17.Change<_i6.MovieSearchState>? change) =>
      super.noSuchMethod(Invocation.method(#onChange, [change]),
          returnValueForMissingStub: null);
  @override
  void addError(Object? error, [StackTrace? stackTrace]) =>
      super.noSuchMethod(Invocation.method(#addError, [error, stackTrace]),
          returnValueForMissingStub: null);
  @override
  void onError(Object? error, StackTrace? stackTrace) =>
      super.noSuchMethod(Invocation.method(#onError, [error, stackTrace]),
          returnValueForMissingStub: null);
}

/// A class which mocks [DetailFilmBloc].
///
/// See the documentation for Mockito's code generation for more information.
class MockDetailFilmBloc extends _i1.Mock implements _i6.DetailFilmBloc {
  MockDetailFilmBloc() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.AmbilDataDetailFilm get getMovieDetail => (super.noSuchMethod(
      Invocation.getter(#getMovieDetail),
      returnValue: _FakeAmbilDataDetailFilm_13()) as _i5.AmbilDataDetailFilm);
  @override
  _i6.StateDetailFilm get state =>
      (super.noSuchMethod(Invocation.getter(#state),
          returnValue: _FakeStateDetailFilm_14()) as _i6.StateDetailFilm);
  @override
  _i8.Stream<_i6.StateDetailFilm> get stream =>
      (super.noSuchMethod(Invocation.getter(#stream),
              returnValue: Stream<_i6.StateDetailFilm>.empty())
          as _i8.Stream<_i6.StateDetailFilm>);
  @override
  bool get isClosed =>
      (super.noSuchMethod(Invocation.getter(#isClosed), returnValue: false)
          as bool);
  @override
  void add(_i6.EventDetailFilm? event) =>
      super.noSuchMethod(Invocation.method(#add, [event]),
          returnValueForMissingStub: null);
  @override
  void onEvent(_i6.EventDetailFilm? event) =>
      super.noSuchMethod(Invocation.method(#onEvent, [event]),
          returnValueForMissingStub: null);
  @override
  void emit(_i6.StateDetailFilm? state) =>
      super.noSuchMethod(Invocation.method(#emit, [state]),
          returnValueForMissingStub: null);
  @override
  void on<E extends _i6.EventDetailFilm>(
          _i17.EventHandler<E, _i6.StateDetailFilm>? handler,
          {_i17.EventTransformer<E>? transformer}) =>
      super.noSuchMethod(
          Invocation.method(#on, [handler], {#transformer: transformer}),
          returnValueForMissingStub: null);
  @override
  void onTransition(
          _i17.Transition<_i6.EventDetailFilm, _i6.StateDetailFilm>?
              transition) =>
      super.noSuchMethod(Invocation.method(#onTransition, [transition]),
          returnValueForMissingStub: null);
  @override
  _i8.Future<void> close() => (super.noSuchMethod(Invocation.method(#close, []),
      returnValue: Future<void>.value(),
      returnValueForMissingStub: Future<void>.value()) as _i8.Future<void>);
  @override
  void onChange(_i17.Change<_i6.StateDetailFilm>? change) =>
      super.noSuchMethod(Invocation.method(#onChange, [change]),
          returnValueForMissingStub: null);
  @override
  void addError(Object? error, [StackTrace? stackTrace]) =>
      super.noSuchMethod(Invocation.method(#addError, [error, stackTrace]),
          returnValueForMissingStub: null);
  @override
  void onError(Object? error, StackTrace? stackTrace) =>
      super.noSuchMethod(Invocation.method(#onError, [error, stackTrace]),
          returnValueForMissingStub: null);
}

/// A class which mocks [DaftarTontonFilmBloc].
///
/// See the documentation for Mockito's code generation for more information.
class MockDaftarTontonFilmBloc extends _i1.Mock
    implements _i6.DaftarTontonFilmBloc {
  MockDaftarTontonFilmBloc() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.ClassStatusDaftarTonton get getWatchListStatus =>
      (super.noSuchMethod(Invocation.getter(#getWatchListStatus),
              returnValue: _FakeClassStatusDaftarTonton_15())
          as _i5.ClassStatusDaftarTonton);
  @override
  _i5.ClassDaftarTontonFilm get getWatchlistMovies =>
      (super.noSuchMethod(Invocation.getter(#getWatchlistMovies),
              returnValue: _FakeClassDaftarTontonFilm_16())
          as _i5.ClassDaftarTontonFilm);
  @override
  _i5.ClassHapusDaftarTonton get removeWatchlist =>
      (super.noSuchMethod(Invocation.getter(#removeWatchlist),
              returnValue: _FakeClassHapusDaftarTonton_17())
          as _i5.ClassHapusDaftarTonton);
  @override
  _i5.ClassSimpanDaftarTonton get saveWatchlist =>
      (super.noSuchMethod(Invocation.getter(#saveWatchlist),
              returnValue: _FakeClassSimpanDaftarTonton_18())
          as _i5.ClassSimpanDaftarTonton);
  @override
  _i6.StateDaftarTontonFilm get state =>
      (super.noSuchMethod(Invocation.getter(#state),
              returnValue: _FakeStateDaftarTontonFilm_19())
          as _i6.StateDaftarTontonFilm);
  @override
  _i8.Stream<_i6.StateDaftarTontonFilm> get stream =>
      (super.noSuchMethod(Invocation.getter(#stream),
              returnValue: Stream<_i6.StateDaftarTontonFilm>.empty())
          as _i8.Stream<_i6.StateDaftarTontonFilm>);
  @override
  bool get isClosed =>
      (super.noSuchMethod(Invocation.getter(#isClosed), returnValue: false)
          as bool);
  @override
  void add(_i6.EventDaftarTontonFilm? event) =>
      super.noSuchMethod(Invocation.method(#add, [event]),
          returnValueForMissingStub: null);
  @override
  void onEvent(_i6.EventDaftarTontonFilm? event) =>
      super.noSuchMethod(Invocation.method(#onEvent, [event]),
          returnValueForMissingStub: null);
  @override
  void emit(_i6.StateDaftarTontonFilm? state) =>
      super.noSuchMethod(Invocation.method(#emit, [state]),
          returnValueForMissingStub: null);
  @override
  void on<E extends _i6.EventDaftarTontonFilm>(
          _i17.EventHandler<E, _i6.StateDaftarTontonFilm>? handler,
          {_i17.EventTransformer<E>? transformer}) =>
      super.noSuchMethod(
          Invocation.method(#on, [handler], {#transformer: transformer}),
          returnValueForMissingStub: null);
  @override
  void onTransition(
          _i17.Transition<_i6.EventDaftarTontonFilm, _i6.StateDaftarTontonFilm>?
              transition) =>
      super.noSuchMethod(Invocation.method(#onTransition, [transition]),
          returnValueForMissingStub: null);
  @override
  _i8.Future<void> close() => (super.noSuchMethod(Invocation.method(#close, []),
      returnValue: Future<void>.value(),
      returnValueForMissingStub: Future<void>.value()) as _i8.Future<void>);
  @override
  void onChange(_i17.Change<_i6.StateDaftarTontonFilm>? change) =>
      super.noSuchMethod(Invocation.method(#onChange, [change]),
          returnValueForMissingStub: null);
  @override
  void addError(Object? error, [StackTrace? stackTrace]) =>
      super.noSuchMethod(Invocation.method(#addError, [error, stackTrace]),
          returnValueForMissingStub: null);
  @override
  void onError(Object? error, StackTrace? stackTrace) =>
      super.noSuchMethod(Invocation.method(#onError, [error, stackTrace]),
          returnValueForMissingStub: null);
}

/// A class which mocks [Client].
///
/// See the documentation for Mockito's code generation for more information.
class MockHttpClient extends _i1.Mock implements _i7.Client {
  MockHttpClient() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i8.Future<_i7.Response> head(Uri? url, {Map<String, String>? headers}) =>
      (super.noSuchMethod(Invocation.method(#head, [url], {#headers: headers}),
              returnValue: Future<_i7.Response>.value(_FakeResponse_20()))
          as _i8.Future<_i7.Response>);
  @override
  _i8.Future<_i7.Response> get(Uri? url, {Map<String, String>? headers}) =>
      (super.noSuchMethod(Invocation.method(#get, [url], {#headers: headers}),
              returnValue: Future<_i7.Response>.value(_FakeResponse_20()))
          as _i8.Future<_i7.Response>);
  @override
  _i8.Future<_i7.Response> post(Uri? url,
          {Map<String, String>? headers,
          Object? body,
          _i18.Encoding? encoding}) =>
      (super.noSuchMethod(
              Invocation.method(#post, [url],
                  {#headers: headers, #body: body, #encoding: encoding}),
              returnValue: Future<_i7.Response>.value(_FakeResponse_20()))
          as _i8.Future<_i7.Response>);
  @override
  _i8.Future<_i7.Response> put(Uri? url,
          {Map<String, String>? headers,
          Object? body,
          _i18.Encoding? encoding}) =>
      (super.noSuchMethod(
              Invocation.method(#put, [url],
                  {#headers: headers, #body: body, #encoding: encoding}),
              returnValue: Future<_i7.Response>.value(_FakeResponse_20()))
          as _i8.Future<_i7.Response>);
  @override
  _i8.Future<_i7.Response> patch(Uri? url,
          {Map<String, String>? headers,
          Object? body,
          _i18.Encoding? encoding}) =>
      (super.noSuchMethod(
              Invocation.method(#patch, [url],
                  {#headers: headers, #body: body, #encoding: encoding}),
              returnValue: Future<_i7.Response>.value(_FakeResponse_20()))
          as _i8.Future<_i7.Response>);
  @override
  _i8.Future<_i7.Response> delete(Uri? url,
          {Map<String, String>? headers,
          Object? body,
          _i18.Encoding? encoding}) =>
      (super.noSuchMethod(
              Invocation.method(#delete, [url],
                  {#headers: headers, #body: body, #encoding: encoding}),
              returnValue: Future<_i7.Response>.value(_FakeResponse_20()))
          as _i8.Future<_i7.Response>);
  @override
  _i8.Future<String> read(Uri? url, {Map<String, String>? headers}) =>
      (super.noSuchMethod(Invocation.method(#read, [url], {#headers: headers}),
          returnValue: Future<String>.value('')) as _i8.Future<String>);
  @override
  _i8.Future<_i19.Uint8List> readBytes(Uri? url,
          {Map<String, String>? headers}) =>
      (super.noSuchMethod(
              Invocation.method(#readBytes, [url], {#headers: headers}),
              returnValue: Future<_i19.Uint8List>.value(_i19.Uint8List(0)))
          as _i8.Future<_i19.Uint8List>);
  @override
  _i8.Future<_i7.StreamedResponse> send(_i7.BaseRequest? request) =>
      (super.noSuchMethod(Invocation.method(#send, [request]),
          returnValue: Future<_i7.StreamedResponse>.value(
              _FakeStreamedResponse_21())) as _i8.Future<_i7.StreamedResponse>);
  @override
  void close() => super.noSuchMethod(Invocation.method(#close, []),
      returnValueForMissingStub: null);
}
