// Mocks generated by Mockito 5.2.0 from annotations
// in cinta_film/test/helpers/test_helper_tvls.dart.
// Do not manually edit this file.

import 'dart:async' as _i7;
import 'dart:convert' as _i17;
import 'dart:typed_data' as _i18;

import 'package:bloc/bloc.dart' as _i15;
import 'package:cinta_film/data/datasources/tvls/tvls_local_data_source.dart'
    as _i11;
import 'package:cinta_film/data/datasources/tvls/tvls_remote_data_source.dart'
    as _i9;
import 'package:cinta_film/data/lib_database.dart' as _i13;
import 'package:cinta_film/data/lib_server_fail.dart' as _i5;
import 'package:cinta_film/data/models/tvls/tvls_detail_model.dart' as _i3;
import 'package:cinta_film/data/models/tvls/tvls_model.dart' as _i10;
import 'package:cinta_film/data/models/tvls/tvls_table.dart' as _i12;
import 'package:cinta_film/domain/entities/tvls/tvls.dart' as _i8;
import 'package:cinta_film/domain/get_data_tv.dart' as _i16;
import 'package:cinta_film/presentasi/bloc/tv_bloc.dart' as _i4;
import 'package:dartz/dartz.dart' as _i2;
import 'package:http/http.dart' as _i6;
import 'package:mockito/mockito.dart' as _i1;
import 'package:sqflite/sqflite.dart' as _i14;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

class _FakeEither_0<L, R> extends _i1.Fake implements _i2.Either<L, R> {}

class _FakeTvlsDetailResponse_1 extends _i1.Fake
    implements _i3.TvlsDetailResponse {}

class _FakeWatchlistTvseriesState_2 extends _i1.Fake
    implements _i4.WatchlistTvseriesState {}

class _FakeTvseriesDetailState_3 extends _i1.Fake
    implements _i4.TvseriesDetailState {}

class _FakeTvseriesSearchState_4 extends _i1.Fake
    implements _i4.TvseriesSearchState {}

class _FakeTopRatedTvseriesState_5 extends _i1.Fake
    implements _i4.TopRatedTvseriesState {}

class _FakeTvseriesRecommendationsState_6 extends _i1.Fake
    implements _i4.TvseriesRecommendationsState {}

class _FakeOnTheAirTvseriesState_7 extends _i1.Fake
    implements _i4.OnTheAirTvseriesState {}

class _FakePopularTvseriesState_8 extends _i1.Fake
    implements _i4.PopularTvseriesState {}

class _FakeTvlsRepository_9 extends _i1.Fake implements _i5.TvlsRepository {}

class _FakeResponse_10 extends _i1.Fake implements _i6.Response {}

class _FakeStreamedResponse_11 extends _i1.Fake
    implements _i6.StreamedResponse {}

/// A class which mocks [TvlsRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockTvlsRepository extends _i1.Mock implements _i5.TvlsRepository {
  MockTvlsRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i7.Future<_i2.Either<_i5.Failure, List<_i8.Tvls>>>
      getserialTvSaatIniDiPutar() =>
          (super.noSuchMethod(Invocation.method(#getserialTvSaatIniDiPutar, []),
                  returnValue:
                      Future<_i2.Either<_i5.Failure, List<_i8.Tvls>>>.value(
                          _FakeEither_0<_i5.Failure, List<_i8.Tvls>>()))
              as _i7.Future<_i2.Either<_i5.Failure, List<_i8.Tvls>>>);
  @override
  _i7.Future<_i2.Either<_i5.Failure, List<_i8.Tvls>>> getPopularTv() =>
      (super.noSuchMethod(Invocation.method(#getPopularTv, []),
          returnValue: Future<_i2.Either<_i5.Failure, List<_i8.Tvls>>>.value(
              _FakeEither_0<_i5.Failure, List<_i8.Tvls>>())) as _i7
          .Future<_i2.Either<_i5.Failure, List<_i8.Tvls>>>);
  @override
  _i7.Future<_i2.Either<_i5.Failure, List<_i8.Tvls>>> getTopRatedTv() =>
      (super.noSuchMethod(Invocation.method(#getTopRatedTv, []),
          returnValue: Future<_i2.Either<_i5.Failure, List<_i8.Tvls>>>.value(
              _FakeEither_0<_i5.Failure, List<_i8.Tvls>>())) as _i7
          .Future<_i2.Either<_i5.Failure, List<_i8.Tvls>>>);
  @override
  _i7.Future<_i2.Either<_i5.Failure, _i8.TvlsDetail>> getTvDetail(int? id) =>
      (super.noSuchMethod(Invocation.method(#getTvDetail, [id]),
          returnValue: Future<_i2.Either<_i5.Failure, _i8.TvlsDetail>>.value(
              _FakeEither_0<_i5.Failure, _i8.TvlsDetail>())) as _i7
          .Future<_i2.Either<_i5.Failure, _i8.TvlsDetail>>);
  @override
  _i7.Future<_i2.Either<_i5.Failure, List<_i8.Tvls>>> getTvRecommendations(
          int? id) =>
      (super.noSuchMethod(Invocation.method(#getTvRecommendations, [id]),
          returnValue: Future<_i2.Either<_i5.Failure, List<_i8.Tvls>>>.value(
              _FakeEither_0<_i5.Failure, List<_i8.Tvls>>())) as _i7
          .Future<_i2.Either<_i5.Failure, List<_i8.Tvls>>>);
  @override
  _i7.Future<_i2.Either<_i5.Failure, List<_i8.Tvls>>> searchTv(String? query) =>
      (super.noSuchMethod(Invocation.method(#searchTv, [query]),
          returnValue: Future<_i2.Either<_i5.Failure, List<_i8.Tvls>>>.value(
              _FakeEither_0<_i5.Failure, List<_i8.Tvls>>())) as _i7
          .Future<_i2.Either<_i5.Failure, List<_i8.Tvls>>>);
  @override
  _i7.Future<_i2.Either<_i5.Failure, String>> savewatchlistTv(
          _i8.TvlsDetail? tv) =>
      (super.noSuchMethod(Invocation.method(#savewatchlistTv, [tv]),
              returnValue: Future<_i2.Either<_i5.Failure, String>>.value(
                  _FakeEither_0<_i5.Failure, String>()))
          as _i7.Future<_i2.Either<_i5.Failure, String>>);
  @override
  _i7.Future<_i2.Either<_i5.Failure, String>> removewatchlistTv(
          _i8.TvlsDetail? tv) =>
      (super.noSuchMethod(Invocation.method(#removewatchlistTv, [tv]),
              returnValue: Future<_i2.Either<_i5.Failure, String>>.value(
                  _FakeEither_0<_i5.Failure, String>()))
          as _i7.Future<_i2.Either<_i5.Failure, String>>);
  @override
  _i7.Future<bool> isAddedTowatchlistTv(int? id) =>
      (super.noSuchMethod(Invocation.method(#isAddedTowatchlistTv, [id]),
          returnValue: Future<bool>.value(false)) as _i7.Future<bool>);
  @override
  _i7.Future<_i2.Either<_i5.Failure, List<_i8.Tvls>>> getwatchlistTv() =>
      (super.noSuchMethod(Invocation.method(#getwatchlistTv, []),
          returnValue: Future<_i2.Either<_i5.Failure, List<_i8.Tvls>>>.value(
              _FakeEither_0<_i5.Failure, List<_i8.Tvls>>())) as _i7
          .Future<_i2.Either<_i5.Failure, List<_i8.Tvls>>>);
}

/// A class which mocks [TvlsRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockTvlsRemoteDataSource extends _i1.Mock
    implements _i9.TvlsRemoteDataSource {
  MockTvlsRemoteDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i7.Future<List<_i10.TvlsModel>> getserialTvSaatIniDiPutar() =>
      (super.noSuchMethod(Invocation.method(#getserialTvSaatIniDiPutar, []),
              returnValue:
                  Future<List<_i10.TvlsModel>>.value(<_i10.TvlsModel>[]))
          as _i7.Future<List<_i10.TvlsModel>>);
  @override
  _i7.Future<List<_i10.TvlsModel>> getPopularTv() => (super.noSuchMethod(
          Invocation.method(#getPopularTv, []),
          returnValue: Future<List<_i10.TvlsModel>>.value(<_i10.TvlsModel>[]))
      as _i7.Future<List<_i10.TvlsModel>>);
  @override
  _i7.Future<List<_i10.TvlsModel>> getTopRatedTv() => (super.noSuchMethod(
          Invocation.method(#getTopRatedTv, []),
          returnValue: Future<List<_i10.TvlsModel>>.value(<_i10.TvlsModel>[]))
      as _i7.Future<List<_i10.TvlsModel>>);
  @override
  _i7.Future<_i3.TvlsDetailResponse> getTvDetail(int? id) =>
      (super.noSuchMethod(Invocation.method(#getTvDetail, [id]),
              returnValue: Future<_i3.TvlsDetailResponse>.value(
                  _FakeTvlsDetailResponse_1()))
          as _i7.Future<_i3.TvlsDetailResponse>);
  @override
  _i7.Future<List<_i10.TvlsModel>> getTvRecommendations(int? id) =>
      (super.noSuchMethod(Invocation.method(#getTvRecommendations, [id]),
              returnValue:
                  Future<List<_i10.TvlsModel>>.value(<_i10.TvlsModel>[]))
          as _i7.Future<List<_i10.TvlsModel>>);
  @override
  _i7.Future<List<_i10.TvlsModel>> searchTv(String? query) =>
      (super.noSuchMethod(Invocation.method(#searchTv, [query]),
              returnValue:
                  Future<List<_i10.TvlsModel>>.value(<_i10.TvlsModel>[]))
          as _i7.Future<List<_i10.TvlsModel>>);
}

/// A class which mocks [TvlsLocalDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockTvlsLocalDataSource extends _i1.Mock
    implements _i11.TvlsLocalDataSource {
  MockTvlsLocalDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i7.Future<String> insertwatchlistTv(_i12.TvlsTable? tv) =>
      (super.noSuchMethod(Invocation.method(#insertwatchlistTv, [tv]),
          returnValue: Future<String>.value('')) as _i7.Future<String>);
  @override
  _i7.Future<String> removewatchlistTv(_i12.TvlsTable? tv) =>
      (super.noSuchMethod(Invocation.method(#removewatchlistTv, [tv]),
          returnValue: Future<String>.value('')) as _i7.Future<String>);
  @override
  _i7.Future<_i12.TvlsTable?> getTvById(int? id) =>
      (super.noSuchMethod(Invocation.method(#getTvById, [id]),
              returnValue: Future<_i12.TvlsTable?>.value())
          as _i7.Future<_i12.TvlsTable?>);
  @override
  _i7.Future<List<_i12.TvlsTable>> getwatchlistTv() => (super.noSuchMethod(
          Invocation.method(#getwatchlistTv, []),
          returnValue: Future<List<_i12.TvlsTable>>.value(<_i12.TvlsTable>[]))
      as _i7.Future<List<_i12.TvlsTable>>);
}

/// A class which mocks [DatabaseHelperTvls].
///
/// See the documentation for Mockito's code generation for more information.
class MockDatabaseHelperTvls extends _i1.Mock
    implements _i13.DatabaseHelperTvls {
  MockDatabaseHelperTvls() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i7.Future<_i14.Database?> get databasetvls =>
      (super.noSuchMethod(Invocation.getter(#databasetvls),
              returnValue: Future<_i14.Database?>.value())
          as _i7.Future<_i14.Database?>);
  @override
  _i7.Future<int> insertwatchlistTv(_i12.TvlsTable? tv) =>
      (super.noSuchMethod(Invocation.method(#insertwatchlistTv, [tv]),
          returnValue: Future<int>.value(0)) as _i7.Future<int>);
  @override
  _i7.Future<int> removewatchlistTv(_i12.TvlsTable? tv) =>
      (super.noSuchMethod(Invocation.method(#removewatchlistTv, [tv]),
          returnValue: Future<int>.value(0)) as _i7.Future<int>);
  @override
  _i7.Future<Map<String, dynamic>?> getTvById(int? id) =>
      (super.noSuchMethod(Invocation.method(#getTvById, [id]),
              returnValue: Future<Map<String, dynamic>?>.value())
          as _i7.Future<Map<String, dynamic>?>);
  @override
  _i7.Future<List<Map<String, dynamic>>> getwatchlistTv() =>
      (super.noSuchMethod(Invocation.method(#getwatchlistTv, []),
              returnValue: Future<List<Map<String, dynamic>>>.value(
                  <Map<String, dynamic>>[]))
          as _i7.Future<List<Map<String, dynamic>>>);
}

/// A class which mocks [WatchlistTvseriesBloc].
///
/// See the documentation for Mockito's code generation for more information.
class MockWatchlistTvseriesBloc extends _i1.Mock
    implements _i4.WatchlistTvseriesBloc {
  MockWatchlistTvseriesBloc() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.WatchlistTvseriesState get state =>
      (super.noSuchMethod(Invocation.getter(#state),
              returnValue: _FakeWatchlistTvseriesState_2())
          as _i4.WatchlistTvseriesState);
  @override
  _i7.Stream<_i4.WatchlistTvseriesState> get stream =>
      (super.noSuchMethod(Invocation.getter(#stream),
              returnValue: Stream<_i4.WatchlistTvseriesState>.empty())
          as _i7.Stream<_i4.WatchlistTvseriesState>);
  @override
  bool get isClosed =>
      (super.noSuchMethod(Invocation.getter(#isClosed), returnValue: false)
          as bool);
  @override
  void add(_i4.WatchlistTvseriesEvent? event) =>
      super.noSuchMethod(Invocation.method(#add, [event]),
          returnValueForMissingStub: null);
  @override
  void onEvent(_i4.WatchlistTvseriesEvent? event) =>
      super.noSuchMethod(Invocation.method(#onEvent, [event]),
          returnValueForMissingStub: null);
  @override
  void emit(_i4.WatchlistTvseriesState? state) =>
      super.noSuchMethod(Invocation.method(#emit, [state]),
          returnValueForMissingStub: null);
  @override
  void on<E extends _i4.WatchlistTvseriesEvent>(
          _i15.EventHandler<E, _i4.WatchlistTvseriesState>? handler,
          {_i15.EventTransformer<E>? transformer}) =>
      super.noSuchMethod(
          Invocation.method(#on, [handler], {#transformer: transformer}),
          returnValueForMissingStub: null);
  @override
  void onTransition(
          _i15.Transition<_i4.WatchlistTvseriesEvent,
                  _i4.WatchlistTvseriesState>?
              transition) =>
      super.noSuchMethod(Invocation.method(#onTransition, [transition]),
          returnValueForMissingStub: null);
  @override
  _i7.Future<void> close() => (super.noSuchMethod(Invocation.method(#close, []),
      returnValue: Future<void>.value(),
      returnValueForMissingStub: Future<void>.value()) as _i7.Future<void>);
  @override
  void onChange(_i15.Change<_i4.WatchlistTvseriesState>? change) =>
      super.noSuchMethod(Invocation.method(#onChange, [change]),
          returnValueForMissingStub: null);
  @override
  void addError(Object? error, [StackTrace? stackTrace]) =>
      super.noSuchMethod(Invocation.method(#addError, [error, stackTrace]),
          returnValueForMissingStub: null);
  @override
  void onError(Object? error, StackTrace? stackTrace) =>
      super.noSuchMethod(Invocation.method(#onError, [error, stackTrace]),
          returnValueForMissingStub: null);
}

/// A class which mocks [TvseriesDetailBloc].
///
/// See the documentation for Mockito's code generation for more information.
class MockTvseriesDetailBloc extends _i1.Mock
    implements _i4.TvseriesDetailBloc {
  MockTvseriesDetailBloc() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.TvseriesDetailState get state => (super.noSuchMethod(
      Invocation.getter(#state),
      returnValue: _FakeTvseriesDetailState_3()) as _i4.TvseriesDetailState);
  @override
  _i7.Stream<_i4.TvseriesDetailState> get stream =>
      (super.noSuchMethod(Invocation.getter(#stream),
              returnValue: Stream<_i4.TvseriesDetailState>.empty())
          as _i7.Stream<_i4.TvseriesDetailState>);
  @override
  bool get isClosed =>
      (super.noSuchMethod(Invocation.getter(#isClosed), returnValue: false)
          as bool);
  @override
  void add(_i4.TvseriesDetailEvent? event) =>
      super.noSuchMethod(Invocation.method(#add, [event]),
          returnValueForMissingStub: null);
  @override
  void onEvent(_i4.TvseriesDetailEvent? event) =>
      super.noSuchMethod(Invocation.method(#onEvent, [event]),
          returnValueForMissingStub: null);
  @override
  void emit(_i4.TvseriesDetailState? state) =>
      super.noSuchMethod(Invocation.method(#emit, [state]),
          returnValueForMissingStub: null);
  @override
  void on<E extends _i4.TvseriesDetailEvent>(
          _i15.EventHandler<E, _i4.TvseriesDetailState>? handler,
          {_i15.EventTransformer<E>? transformer}) =>
      super.noSuchMethod(
          Invocation.method(#on, [handler], {#transformer: transformer}),
          returnValueForMissingStub: null);
  @override
  void onTransition(
          _i15.Transition<_i4.TvseriesDetailEvent, _i4.TvseriesDetailState>?
              transition) =>
      super.noSuchMethod(Invocation.method(#onTransition, [transition]),
          returnValueForMissingStub: null);
  @override
  _i7.Future<void> close() => (super.noSuchMethod(Invocation.method(#close, []),
      returnValue: Future<void>.value(),
      returnValueForMissingStub: Future<void>.value()) as _i7.Future<void>);
  @override
  void onChange(_i15.Change<_i4.TvseriesDetailState>? change) =>
      super.noSuchMethod(Invocation.method(#onChange, [change]),
          returnValueForMissingStub: null);
  @override
  void addError(Object? error, [StackTrace? stackTrace]) =>
      super.noSuchMethod(Invocation.method(#addError, [error, stackTrace]),
          returnValueForMissingStub: null);
  @override
  void onError(Object? error, StackTrace? stackTrace) =>
      super.noSuchMethod(Invocation.method(#onError, [error, stackTrace]),
          returnValueForMissingStub: null);
}

/// A class which mocks [TvseriesSearchBloc].
///
/// See the documentation for Mockito's code generation for more information.
class MockTvseriesSearchBloc extends _i1.Mock
    implements _i4.TvseriesSearchBloc {
  MockTvseriesSearchBloc() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.TvseriesSearchState get state => (super.noSuchMethod(
      Invocation.getter(#state),
      returnValue: _FakeTvseriesSearchState_4()) as _i4.TvseriesSearchState);
  @override
  _i7.Stream<_i4.TvseriesSearchState> get stream =>
      (super.noSuchMethod(Invocation.getter(#stream),
              returnValue: Stream<_i4.TvseriesSearchState>.empty())
          as _i7.Stream<_i4.TvseriesSearchState>);
  @override
  bool get isClosed =>
      (super.noSuchMethod(Invocation.getter(#isClosed), returnValue: false)
          as bool);
  @override
  void add(_i4.TvseriesSearchEvent? event) =>
      super.noSuchMethod(Invocation.method(#add, [event]),
          returnValueForMissingStub: null);
  @override
  void onEvent(_i4.TvseriesSearchEvent? event) =>
      super.noSuchMethod(Invocation.method(#onEvent, [event]),
          returnValueForMissingStub: null);
  @override
  void emit(_i4.TvseriesSearchState? state) =>
      super.noSuchMethod(Invocation.method(#emit, [state]),
          returnValueForMissingStub: null);
  @override
  void on<E extends _i4.TvseriesSearchEvent>(
          _i15.EventHandler<E, _i4.TvseriesSearchState>? handler,
          {_i15.EventTransformer<E>? transformer}) =>
      super.noSuchMethod(
          Invocation.method(#on, [handler], {#transformer: transformer}),
          returnValueForMissingStub: null);
  @override
  void onTransition(
          _i15.Transition<_i4.TvseriesSearchEvent, _i4.TvseriesSearchState>?
              transition) =>
      super.noSuchMethod(Invocation.method(#onTransition, [transition]),
          returnValueForMissingStub: null);
  @override
  _i7.Future<void> close() => (super.noSuchMethod(Invocation.method(#close, []),
      returnValue: Future<void>.value(),
      returnValueForMissingStub: Future<void>.value()) as _i7.Future<void>);
  @override
  void onChange(_i15.Change<_i4.TvseriesSearchState>? change) =>
      super.noSuchMethod(Invocation.method(#onChange, [change]),
          returnValueForMissingStub: null);
  @override
  void addError(Object? error, [StackTrace? stackTrace]) =>
      super.noSuchMethod(Invocation.method(#addError, [error, stackTrace]),
          returnValueForMissingStub: null);
  @override
  void onError(Object? error, StackTrace? stackTrace) =>
      super.noSuchMethod(Invocation.method(#onError, [error, stackTrace]),
          returnValueForMissingStub: null);
}

/// A class which mocks [TopRatedTvseriesBloc].
///
/// See the documentation for Mockito's code generation for more information.
class MockTopRatedTvseriesBloc extends _i1.Mock
    implements _i4.TopRatedTvseriesBloc {
  MockTopRatedTvseriesBloc() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.TopRatedTvseriesState get state =>
      (super.noSuchMethod(Invocation.getter(#state),
              returnValue: _FakeTopRatedTvseriesState_5())
          as _i4.TopRatedTvseriesState);
  @override
  _i7.Stream<_i4.TopRatedTvseriesState> get stream =>
      (super.noSuchMethod(Invocation.getter(#stream),
              returnValue: Stream<_i4.TopRatedTvseriesState>.empty())
          as _i7.Stream<_i4.TopRatedTvseriesState>);
  @override
  bool get isClosed =>
      (super.noSuchMethod(Invocation.getter(#isClosed), returnValue: false)
          as bool);
  @override
  void add(_i4.TopRatedTvseriesEvent? event) =>
      super.noSuchMethod(Invocation.method(#add, [event]),
          returnValueForMissingStub: null);
  @override
  void onEvent(_i4.TopRatedTvseriesEvent? event) =>
      super.noSuchMethod(Invocation.method(#onEvent, [event]),
          returnValueForMissingStub: null);
  @override
  void emit(_i4.TopRatedTvseriesState? state) =>
      super.noSuchMethod(Invocation.method(#emit, [state]),
          returnValueForMissingStub: null);
  @override
  void on<E extends _i4.TopRatedTvseriesEvent>(
          _i15.EventHandler<E, _i4.TopRatedTvseriesState>? handler,
          {_i15.EventTransformer<E>? transformer}) =>
      super.noSuchMethod(
          Invocation.method(#on, [handler], {#transformer: transformer}),
          returnValueForMissingStub: null);
  @override
  void onTransition(
          _i15.Transition<_i4.TopRatedTvseriesEvent, _i4.TopRatedTvseriesState>?
              transition) =>
      super.noSuchMethod(Invocation.method(#onTransition, [transition]),
          returnValueForMissingStub: null);
  @override
  _i7.Future<void> close() => (super.noSuchMethod(Invocation.method(#close, []),
      returnValue: Future<void>.value(),
      returnValueForMissingStub: Future<void>.value()) as _i7.Future<void>);
  @override
  void onChange(_i15.Change<_i4.TopRatedTvseriesState>? change) =>
      super.noSuchMethod(Invocation.method(#onChange, [change]),
          returnValueForMissingStub: null);
  @override
  void addError(Object? error, [StackTrace? stackTrace]) =>
      super.noSuchMethod(Invocation.method(#addError, [error, stackTrace]),
          returnValueForMissingStub: null);
  @override
  void onError(Object? error, StackTrace? stackTrace) =>
      super.noSuchMethod(Invocation.method(#onError, [error, stackTrace]),
          returnValueForMissingStub: null);
}

/// A class which mocks [TvseriesRecommendationsBloc].
///
/// See the documentation for Mockito's code generation for more information.
class MockTvseriesRecommendationsBloc extends _i1.Mock
    implements _i4.TvseriesRecommendationsBloc {
  MockTvseriesRecommendationsBloc() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.TvseriesRecommendationsState get state =>
      (super.noSuchMethod(Invocation.getter(#state),
              returnValue: _FakeTvseriesRecommendationsState_6())
          as _i4.TvseriesRecommendationsState);
  @override
  _i7.Stream<_i4.TvseriesRecommendationsState> get stream =>
      (super.noSuchMethod(Invocation.getter(#stream),
              returnValue: Stream<_i4.TvseriesRecommendationsState>.empty())
          as _i7.Stream<_i4.TvseriesRecommendationsState>);
  @override
  bool get isClosed =>
      (super.noSuchMethod(Invocation.getter(#isClosed), returnValue: false)
          as bool);
  @override
  void add(_i4.TvseriesRecommendationsEvent? event) =>
      super.noSuchMethod(Invocation.method(#add, [event]),
          returnValueForMissingStub: null);
  @override
  void onEvent(_i4.TvseriesRecommendationsEvent? event) =>
      super.noSuchMethod(Invocation.method(#onEvent, [event]),
          returnValueForMissingStub: null);
  @override
  void emit(_i4.TvseriesRecommendationsState? state) =>
      super.noSuchMethod(Invocation.method(#emit, [state]),
          returnValueForMissingStub: null);
  @override
  void on<E extends _i4.TvseriesRecommendationsEvent>(
          _i15.EventHandler<E, _i4.TvseriesRecommendationsState>? handler,
          {_i15.EventTransformer<E>? transformer}) =>
      super.noSuchMethod(
          Invocation.method(#on, [handler], {#transformer: transformer}),
          returnValueForMissingStub: null);
  @override
  void onTransition(
          _i15.Transition<_i4.TvseriesRecommendationsEvent,
                  _i4.TvseriesRecommendationsState>?
              transition) =>
      super.noSuchMethod(Invocation.method(#onTransition, [transition]),
          returnValueForMissingStub: null);
  @override
  _i7.Future<void> close() => (super.noSuchMethod(Invocation.method(#close, []),
      returnValue: Future<void>.value(),
      returnValueForMissingStub: Future<void>.value()) as _i7.Future<void>);
  @override
  void onChange(_i15.Change<_i4.TvseriesRecommendationsState>? change) =>
      super.noSuchMethod(Invocation.method(#onChange, [change]),
          returnValueForMissingStub: null);
  @override
  void addError(Object? error, [StackTrace? stackTrace]) =>
      super.noSuchMethod(Invocation.method(#addError, [error, stackTrace]),
          returnValueForMissingStub: null);
  @override
  void onError(Object? error, StackTrace? stackTrace) =>
      super.noSuchMethod(Invocation.method(#onError, [error, stackTrace]),
          returnValueForMissingStub: null);
}

/// A class which mocks [OnTheAirTvseriesBloc].
///
/// See the documentation for Mockito's code generation for more information.
class MockOnTheAirTvseriesBloc extends _i1.Mock
    implements _i4.OnTheAirTvseriesBloc {
  MockOnTheAirTvseriesBloc() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.OnTheAirTvseriesState get state =>
      (super.noSuchMethod(Invocation.getter(#state),
              returnValue: _FakeOnTheAirTvseriesState_7())
          as _i4.OnTheAirTvseriesState);
  @override
  _i7.Stream<_i4.OnTheAirTvseriesState> get stream =>
      (super.noSuchMethod(Invocation.getter(#stream),
              returnValue: Stream<_i4.OnTheAirTvseriesState>.empty())
          as _i7.Stream<_i4.OnTheAirTvseriesState>);
  @override
  bool get isClosed =>
      (super.noSuchMethod(Invocation.getter(#isClosed), returnValue: false)
          as bool);
  @override
  void add(_i4.OnTheAirTvseriesEvent? event) =>
      super.noSuchMethod(Invocation.method(#add, [event]),
          returnValueForMissingStub: null);
  @override
  void onEvent(_i4.OnTheAirTvseriesEvent? event) =>
      super.noSuchMethod(Invocation.method(#onEvent, [event]),
          returnValueForMissingStub: null);
  @override
  void emit(_i4.OnTheAirTvseriesState? state) =>
      super.noSuchMethod(Invocation.method(#emit, [state]),
          returnValueForMissingStub: null);
  @override
  void on<E extends _i4.OnTheAirTvseriesEvent>(
          _i15.EventHandler<E, _i4.OnTheAirTvseriesState>? handler,
          {_i15.EventTransformer<E>? transformer}) =>
      super.noSuchMethod(
          Invocation.method(#on, [handler], {#transformer: transformer}),
          returnValueForMissingStub: null);
  @override
  void onTransition(
          _i15.Transition<_i4.OnTheAirTvseriesEvent, _i4.OnTheAirTvseriesState>?
              transition) =>
      super.noSuchMethod(Invocation.method(#onTransition, [transition]),
          returnValueForMissingStub: null);
  @override
  _i7.Future<void> close() => (super.noSuchMethod(Invocation.method(#close, []),
      returnValue: Future<void>.value(),
      returnValueForMissingStub: Future<void>.value()) as _i7.Future<void>);
  @override
  void onChange(_i15.Change<_i4.OnTheAirTvseriesState>? change) =>
      super.noSuchMethod(Invocation.method(#onChange, [change]),
          returnValueForMissingStub: null);
  @override
  void addError(Object? error, [StackTrace? stackTrace]) =>
      super.noSuchMethod(Invocation.method(#addError, [error, stackTrace]),
          returnValueForMissingStub: null);
  @override
  void onError(Object? error, StackTrace? stackTrace) =>
      super.noSuchMethod(Invocation.method(#onError, [error, stackTrace]),
          returnValueForMissingStub: null);
}

/// A class which mocks [PopularTvseriesBloc].
///
/// See the documentation for Mockito's code generation for more information.
class MockPopularTvseriesBloc extends _i1.Mock
    implements _i4.PopularTvseriesBloc {
  MockPopularTvseriesBloc() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.PopularTvseriesState get state => (super.noSuchMethod(
      Invocation.getter(#state),
      returnValue: _FakePopularTvseriesState_8()) as _i4.PopularTvseriesState);
  @override
  _i7.Stream<_i4.PopularTvseriesState> get stream =>
      (super.noSuchMethod(Invocation.getter(#stream),
              returnValue: Stream<_i4.PopularTvseriesState>.empty())
          as _i7.Stream<_i4.PopularTvseriesState>);
  @override
  bool get isClosed =>
      (super.noSuchMethod(Invocation.getter(#isClosed), returnValue: false)
          as bool);
  @override
  void add(_i4.PopularTvseriesEvent? event) =>
      super.noSuchMethod(Invocation.method(#add, [event]),
          returnValueForMissingStub: null);
  @override
  void onEvent(_i4.PopularTvseriesEvent? event) =>
      super.noSuchMethod(Invocation.method(#onEvent, [event]),
          returnValueForMissingStub: null);
  @override
  void emit(_i4.PopularTvseriesState? state) =>
      super.noSuchMethod(Invocation.method(#emit, [state]),
          returnValueForMissingStub: null);
  @override
  void on<E extends _i4.PopularTvseriesEvent>(
          _i15.EventHandler<E, _i4.PopularTvseriesState>? handler,
          {_i15.EventTransformer<E>? transformer}) =>
      super.noSuchMethod(
          Invocation.method(#on, [handler], {#transformer: transformer}),
          returnValueForMissingStub: null);
  @override
  void onTransition(
          _i15.Transition<_i4.PopularTvseriesEvent, _i4.PopularTvseriesState>?
              transition) =>
      super.noSuchMethod(Invocation.method(#onTransition, [transition]),
          returnValueForMissingStub: null);
  @override
  _i7.Future<void> close() => (super.noSuchMethod(Invocation.method(#close, []),
      returnValue: Future<void>.value(),
      returnValueForMissingStub: Future<void>.value()) as _i7.Future<void>);
  @override
  void onChange(_i15.Change<_i4.PopularTvseriesState>? change) =>
      super.noSuchMethod(Invocation.method(#onChange, [change]),
          returnValueForMissingStub: null);
  @override
  void addError(Object? error, [StackTrace? stackTrace]) =>
      super.noSuchMethod(Invocation.method(#addError, [error, stackTrace]),
          returnValueForMissingStub: null);
  @override
  void onError(Object? error, StackTrace? stackTrace) =>
      super.noSuchMethod(Invocation.method(#onError, [error, stackTrace]),
          returnValueForMissingStub: null);
}

/// A class which mocks [GetserialTvSaatIniDiPutarls].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetserialTvSaatIniDiPutarls extends _i1.Mock
    implements _i16.GetserialTvSaatIniDiPutarls {
  MockGetserialTvSaatIniDiPutarls() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.TvlsRepository get repository =>
      (super.noSuchMethod(Invocation.getter(#repository),
          returnValue: _FakeTvlsRepository_9()) as _i5.TvlsRepository);
  @override
  _i7.Future<_i2.Either<_i5.Failure, List<_i8.Tvls>>> execute() =>
      (super.noSuchMethod(Invocation.method(#execute, []),
          returnValue: Future<_i2.Either<_i5.Failure, List<_i8.Tvls>>>.value(
              _FakeEither_0<_i5.Failure, List<_i8.Tvls>>())) as _i7
          .Future<_i2.Either<_i5.Failure, List<_i8.Tvls>>>);
}

/// A class which mocks [GetPopularTvls].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetPopularTvls extends _i1.Mock implements _i16.GetPopularTvls {
  MockGetPopularTvls() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.TvlsRepository get repository =>
      (super.noSuchMethod(Invocation.getter(#repository),
          returnValue: _FakeTvlsRepository_9()) as _i5.TvlsRepository);
  @override
  _i7.Future<_i2.Either<_i5.Failure, List<_i8.Tvls>>> execute() =>
      (super.noSuchMethod(Invocation.method(#execute, []),
          returnValue: Future<_i2.Either<_i5.Failure, List<_i8.Tvls>>>.value(
              _FakeEither_0<_i5.Failure, List<_i8.Tvls>>())) as _i7
          .Future<_i2.Either<_i5.Failure, List<_i8.Tvls>>>);
}

/// A class which mocks [GetTopRatedTvls].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetTopRatedTvls extends _i1.Mock implements _i16.GetTopRatedTvls {
  MockGetTopRatedTvls() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.TvlsRepository get repository =>
      (super.noSuchMethod(Invocation.getter(#repository),
          returnValue: _FakeTvlsRepository_9()) as _i5.TvlsRepository);
  @override
  _i7.Future<_i2.Either<_i5.Failure, List<_i8.Tvls>>> execute() =>
      (super.noSuchMethod(Invocation.method(#execute, []),
          returnValue: Future<_i2.Either<_i5.Failure, List<_i8.Tvls>>>.value(
              _FakeEither_0<_i5.Failure, List<_i8.Tvls>>())) as _i7
          .Future<_i2.Either<_i5.Failure, List<_i8.Tvls>>>);
}

/// A class which mocks [GetTvlsDetail].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetTvlsDetail extends _i1.Mock implements _i16.GetTvlsDetail {
  MockGetTvlsDetail() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.TvlsRepository get repository =>
      (super.noSuchMethod(Invocation.getter(#repository),
          returnValue: _FakeTvlsRepository_9()) as _i5.TvlsRepository);
  @override
  _i7.Future<_i2.Either<_i5.Failure, _i8.TvlsDetail>> execute(int? id) =>
      (super.noSuchMethod(Invocation.method(#execute, [id]),
          returnValue: Future<_i2.Either<_i5.Failure, _i8.TvlsDetail>>.value(
              _FakeEither_0<_i5.Failure, _i8.TvlsDetail>())) as _i7
          .Future<_i2.Either<_i5.Failure, _i8.TvlsDetail>>);
}

/// A class which mocks [GetTvlsRecommendations].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetTvlsRecommendations extends _i1.Mock
    implements _i16.GetTvlsRecommendations {
  MockGetTvlsRecommendations() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.TvlsRepository get repository =>
      (super.noSuchMethod(Invocation.getter(#repository),
          returnValue: _FakeTvlsRepository_9()) as _i5.TvlsRepository);
  @override
  _i7.Future<_i2.Either<_i5.Failure, List<_i8.Tvls>>> execute(dynamic id) =>
      (super.noSuchMethod(Invocation.method(#execute, [id]),
          returnValue: Future<_i2.Either<_i5.Failure, List<_i8.Tvls>>>.value(
              _FakeEither_0<_i5.Failure, List<_i8.Tvls>>())) as _i7
          .Future<_i2.Either<_i5.Failure, List<_i8.Tvls>>>);
}

/// A class which mocks [ClassStatusDaftarTontonTvls].
///
/// See the documentation for Mockito's code generation for more information.
class MockClassStatusDaftarTontonTvls extends _i1.Mock
    implements _i16.ClassStatusDaftarTontonTvls {
  MockClassStatusDaftarTontonTvls() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.TvlsRepository get repository =>
      (super.noSuchMethod(Invocation.getter(#repository),
          returnValue: _FakeTvlsRepository_9()) as _i5.TvlsRepository);
  @override
  _i7.Future<bool> execute(int? id) =>
      (super.noSuchMethod(Invocation.method(#execute, [id]),
          returnValue: Future<bool>.value(false)) as _i7.Future<bool>);
}

/// A class which mocks [GetwatchlistTvls].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetwatchlistTvls extends _i1.Mock implements _i16.GetwatchlistTvls {
  MockGetwatchlistTvls() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i7.Future<_i2.Either<_i5.Failure, List<_i8.Tvls>>> execute() =>
      (super.noSuchMethod(Invocation.method(#execute, []),
          returnValue: Future<_i2.Either<_i5.Failure, List<_i8.Tvls>>>.value(
              _FakeEither_0<_i5.Failure, List<_i8.Tvls>>())) as _i7
          .Future<_i2.Either<_i5.Failure, List<_i8.Tvls>>>);
}

/// A class which mocks [ClassHapusDaftarTontonTvls].
///
/// See the documentation for Mockito's code generation for more information.
class MockClassHapusDaftarTontonTvls extends _i1.Mock
    implements _i16.ClassHapusDaftarTontonTvls {
  MockClassHapusDaftarTontonTvls() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.TvlsRepository get repository =>
      (super.noSuchMethod(Invocation.getter(#repository),
          returnValue: _FakeTvlsRepository_9()) as _i5.TvlsRepository);
  @override
  _i7.Future<_i2.Either<_i5.Failure, String>> execute(_i8.TvlsDetail? tv) =>
      (super.noSuchMethod(Invocation.method(#execute, [tv]),
              returnValue: Future<_i2.Either<_i5.Failure, String>>.value(
                  _FakeEither_0<_i5.Failure, String>()))
          as _i7.Future<_i2.Either<_i5.Failure, String>>);
}

/// A class which mocks [ClassSimpanDaftarTontonTvls].
///
/// See the documentation for Mockito's code generation for more information.
class MockClassSimpanDaftarTontonTvls extends _i1.Mock
    implements _i16.ClassSimpanDaftarTontonTvls {
  MockClassSimpanDaftarTontonTvls() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.TvlsRepository get repository =>
      (super.noSuchMethod(Invocation.getter(#repository),
          returnValue: _FakeTvlsRepository_9()) as _i5.TvlsRepository);
  @override
  _i7.Future<_i2.Either<_i5.Failure, String>> execute(_i8.TvlsDetail? tv) =>
      (super.noSuchMethod(Invocation.method(#execute, [tv]),
              returnValue: Future<_i2.Either<_i5.Failure, String>>.value(
                  _FakeEither_0<_i5.Failure, String>()))
          as _i7.Future<_i2.Either<_i5.Failure, String>>);
}

/// A class which mocks [SearchTvls].
///
/// See the documentation for Mockito's code generation for more information.
class MockSearchTvls extends _i1.Mock implements _i16.SearchTvls {
  MockSearchTvls() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.TvlsRepository get repository =>
      (super.noSuchMethod(Invocation.getter(#repository),
          returnValue: _FakeTvlsRepository_9()) as _i5.TvlsRepository);
  @override
  _i7.Future<_i2.Either<_i5.Failure, List<_i8.Tvls>>> execute(String? query) =>
      (super.noSuchMethod(Invocation.method(#execute, [query]),
          returnValue: Future<_i2.Either<_i5.Failure, List<_i8.Tvls>>>.value(
              _FakeEither_0<_i5.Failure, List<_i8.Tvls>>())) as _i7
          .Future<_i2.Either<_i5.Failure, List<_i8.Tvls>>>);
}

/// A class which mocks [Client].
///
/// See the documentation for Mockito's code generation for more information.
class MockHttpClient extends _i1.Mock implements _i6.Client {
  MockHttpClient() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i7.Future<_i6.Response> head(Uri? url, {Map<String, String>? headers}) =>
      (super.noSuchMethod(Invocation.method(#head, [url], {#headers: headers}),
              returnValue: Future<_i6.Response>.value(_FakeResponse_10()))
          as _i7.Future<_i6.Response>);
  @override
  _i7.Future<_i6.Response> get(Uri? url, {Map<String, String>? headers}) =>
      (super.noSuchMethod(Invocation.method(#get, [url], {#headers: headers}),
              returnValue: Future<_i6.Response>.value(_FakeResponse_10()))
          as _i7.Future<_i6.Response>);
  @override
  _i7.Future<_i6.Response> post(Uri? url,
          {Map<String, String>? headers,
          Object? body,
          _i17.Encoding? encoding}) =>
      (super.noSuchMethod(
              Invocation.method(#post, [url],
                  {#headers: headers, #body: body, #encoding: encoding}),
              returnValue: Future<_i6.Response>.value(_FakeResponse_10()))
          as _i7.Future<_i6.Response>);
  @override
  _i7.Future<_i6.Response> put(Uri? url,
          {Map<String, String>? headers,
          Object? body,
          _i17.Encoding? encoding}) =>
      (super.noSuchMethod(
              Invocation.method(#put, [url],
                  {#headers: headers, #body: body, #encoding: encoding}),
              returnValue: Future<_i6.Response>.value(_FakeResponse_10()))
          as _i7.Future<_i6.Response>);
  @override
  _i7.Future<_i6.Response> patch(Uri? url,
          {Map<String, String>? headers,
          Object? body,
          _i17.Encoding? encoding}) =>
      (super.noSuchMethod(
              Invocation.method(#patch, [url],
                  {#headers: headers, #body: body, #encoding: encoding}),
              returnValue: Future<_i6.Response>.value(_FakeResponse_10()))
          as _i7.Future<_i6.Response>);
  @override
  _i7.Future<_i6.Response> delete(Uri? url,
          {Map<String, String>? headers,
          Object? body,
          _i17.Encoding? encoding}) =>
      (super.noSuchMethod(
              Invocation.method(#delete, [url],
                  {#headers: headers, #body: body, #encoding: encoding}),
              returnValue: Future<_i6.Response>.value(_FakeResponse_10()))
          as _i7.Future<_i6.Response>);
  @override
  _i7.Future<String> read(Uri? url, {Map<String, String>? headers}) =>
      (super.noSuchMethod(Invocation.method(#read, [url], {#headers: headers}),
          returnValue: Future<String>.value('')) as _i7.Future<String>);
  @override
  _i7.Future<_i18.Uint8List> readBytes(Uri? url,
          {Map<String, String>? headers}) =>
      (super.noSuchMethod(
              Invocation.method(#readBytes, [url], {#headers: headers}),
              returnValue: Future<_i18.Uint8List>.value(_i18.Uint8List(0)))
          as _i7.Future<_i18.Uint8List>);
  @override
  _i7.Future<_i6.StreamedResponse> send(_i6.BaseRequest? request) =>
      (super.noSuchMethod(Invocation.method(#send, [request]),
          returnValue: Future<_i6.StreamedResponse>.value(
              _FakeStreamedResponse_11())) as _i7.Future<_i6.StreamedResponse>);
  @override
  void close() => super.noSuchMethod(Invocation.method(#close, []),
      returnValueForMissingStub: null);
}
